### ISSUE TITLE
Update package to version 2.8

### ISSUE THREAD

**Issue by innerout** [conda-forge/cppcheck-feedstock#54]
### Comment:

It is my first issue on a conda feedstock, so I am sorry if I am breaking a rule. I saw that there are some pending PRs to update to 2.7.2. However, the latest version of the package is 2.8. Is there a way to go to version 2.8? Although I am a beginner, I would like to help if it is possible.

**Comment by timsnyder** [comment]
Hi @innerout ,  I was able to confirm that the bot stopped opening new PR's because there were too many open.  I'm going to try to get the latest bot PR merged and close the older ones, then 2.8 should be created and I'll get that pushed too.

**Comment by innerout** [comment]
Hi @timsnyder, I appreciate the feedback. I will wait for the latest version to be merged then.

**Comment by timsnyder** [comment]
Hi @innerout , do you happen to have a `osx_arm64` machine?  The 2.8 build is failling on the ARM builds for macos as I mentioned in https://github.com/conda-forge/cppcheck-feedstock/pull/59#issuecomment-1169529211.  If you have an arm-based mac and any thoughts on how to fix those builds, it would be helpful.

**Comment by innerout** [comment]
I am completely inexperienced with ARM and macOS, and I don't have an ARM or a macOS machine, but from a brief search, people report that setting zsh as the default shell fixes the problem. https://discussions.apple.com/thread/250777998

Also, I found these, but I don't think that's the case here. Maybe the 2nd one may fix the problem.
https://stackoverflow.com/questions/72006530/bad-cpu-type-in-executable-mac-intel-core
https://www.journaldev.com/51374/bad-cpu-type-in-executable-fixed

**Comment by timsnyder** [comment]
Sorry for the delay on this.  I was able to figure out wny the `osx_arm64` builds are failing (see #69) and disabled them for now.  2.10.1 should be available from anaconda.org in a while.
