### ISSUE TITLE
Re-enable `osx_arm64` builds

### ISSUE THREAD

**Issue by timsnyder** [conda-forge/cppcheck-feedstock#69]
the `osx_arm64` builds are failing because they are cross-compiling and cppcheck builds something called dmake that it uses in it's build.  It appears to be cross-compiling dmake but wants to run it on the build host and that's wrong.

cmake explains that you have to do a native build first and then supply the path to your native built binaries in their docs at https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html#running-executables-built-in-the-project

_Originally posted by @timsnyder in https://github.com/conda-forge/cppcheck-feedstock/issues/66#issuecomment-1445270658_

**Comment by timsnyder** [comment]
Isuru pointed me to https://github.com/conda-forge/paraview-feedstock/blob/d4bebebea209add89221528dc524d00fd8c1bbf0/recipe/build.sh#L18-L20 in the gitter

**Comment by wolfv** [comment]
Done in #85
